name: mlworkshop
channels:
  - conda-forge
  - defaults
dependencies:
- scipy
- numpy
- jinja2
- jsonschema
- jupyter
- jupyter_client
- jupyter_console
- jupyter_core
- conda-forge::jupyter_contrib_nbextensions  
- matplotlib
- openssl
- pandas
- pandocfilters
- path.py
- patsy
- pcre
- pexpect
- pip
- prompt_toolkit
- python>=3.6.0
- python-dateutil
- pytz
- pyzmq
- seaborn
- setuptools
- simplegeneric
- sip
- six
- wheel
- widgetsnbextension
- xz
- pytest
- pip:
  - awscli==1.15.32
  - bson==0.5.6
  - environment-kernels==1.1.1
  - future==0.16.0
  - py4j==0.10.6
  - pyasn1==0.4.3
  - pyathena==1.2.5
  - pygal==2.4.0
  - pyspark==2.3.0
  - pytube==9.2.2
  - rsa==3.4.2
  - sagemaker==1.4.1
  - sagemaker-pyspark==1.1.0
  - tables==3.4.3
  - tenacity==4.12.0
