name: demo_p36
channels:
  - conda-forge
  - defaults
dependencies:
- scipy
- cuda90
- cudnn
- numpy
- pillow
- jpeg
- spacy
- zlib
- freetype
- libtiff
- bleach
- certifi
- cffi
- cycler
- decorator
- entrypoints
- expat
- html5lib
- icu
- ipykernel
- ipython
- ipython_genutils
- ipywidgets
- jedi
- jinja2
- jsonschema
- jupyter
- jupyter_client
- jupyter_console
- jupyter_core
- conda-forge::jupyter_contrib_nbextensions  
- libiconv
- libpng
- libsodium
- libxml2
- markupsafe
- matplotlib
- mistune
- mkl
- nbconvert
- nbformat
- notebook
- numpy
- olefile
- openssl
- pandas
- pandocfilters
- path.py
- patsy
- pcre
- pexpect
- pickleshare
- pillow
- pip
- prompt_toolkit
- pycparser
- pygments
- pyparsing
- pyqt
- python>=3.6.0
- python-dateutil
- pytz
- pyzmq
- qt
- qtconsole
- scipy
- seaborn
- setuptools
- simplegeneric
- sip
- six
- sqlite
- statsmodels
- testpath
- tk
- tornado<5
- tqdm
- traitlets
- wcwidth
- wheel
- widgetsnbextension
- xz
- zeromq
- bcolz
- prompt_toolkit
- pytest
- pip:
  - awscli==1.15.32
  - bson==0.5.6
  - environment-kernels==1.1.1
  - future==0.16.0
  - py4j==0.10.6
  - pyasn1==0.4.3
  - pyathena==1.2.5
  - pygal==2.4.0
  - pyspark==2.3.0
  - pytube==9.2.2
  - rsa==3.4.2
  - sagemaker==1.4.1
  - sagemaker-pyspark==1.1.0
  - tables==3.4.3
  - tenacity==4.12.0
